name = input("What s your name? ")
file = open("name.txt" , "w")
file.write(name)
print("Saving...")
file.close()
file = open("name.txt" , "r")
print("Loading....")
content = file.read()
print("Saved name:", content)